cart/urls.py
# coding: utf-8
from django.conf.urls import url
import views


urlpatterns = [
    # Страница корзины
    url(r'^$', views.cart, name='cart'),
    # Страница добавления товара
    url(r'^add/$', views.add, name='add'),
    # Страница удаления товара
    url(r'^remove/$', views.remove, name='remove'),
    # Страница оплаты
    url(r'^order/$', views.order, name='order'),
    # Страница благодарности
    url(r'^thanks/(?P<order_id>[0-9]+)/$', views.thanks, name='thanks'),
    # Страница с детализацией заказа
    url(r'^order/(?P<secret>[\w-]+)/$', views.order_detail, name='order_item'),
]

catalog/urls.py
from django.conf.urls import url
import views


urlpatterns = [
    url(r'^$', views.catalog, name='catalog'),
    url(r'^(?P<product_slug>[a-zA-Z0-9-_.]+)$', views.product, name='product'),
]

comments/urls.py
from django.conf.urls import url
import views


urlpatterns = [
    url(r'^$', views.comment, name='comment'),
]

main/urls.py
from django.conf.urls import url
import views


urlpatterns = [
    url(r'^$', views.main, name='main'),
]

vr_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
import settings


urlpatterns = [
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^', include('main.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^catalog/', include('catalog.urls')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^comments/', include('comments.urls', namespace='comments')),
    url(r'^catalog/ajax/', include('catalog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/models.py
# coding: utf-8
from __future__ import unicode_literals
from django.db import models
from catalog.models import Product
from django.core.urlresolvers import reverse
import uuid


PAYMENT_TYPE = (
    ('Cash', u'Наличными'),
    ('Internet', u'Электронными'),
)


class Cart(models.Model):
    add_date = models.DateTimeField(u'Время добавления', auto_now_add=True)

    def __unicode__(self):
        return self.add_date.strftime('%Y-%m-%d   %H:%M:%S')

    class Meta:
        verbose_name = "корзина"
        verbose_name_plural = "Корзины"

    def total_price(self):
        result = 0
        for item in self.products_in_cart.all():
            result += item.product.price * item.quantity
        return result

    def get_products(self):
        return self.products_in_cart.all()

    get_products.short_description = 'Products'


class ProductInCart(models.Model):
    cart = models.ForeignKey(Cart, related_name='products_in_cart')

    product = models.ForeignKey(Product, verbose_name="Продукт", related_name='product')
    quantity = models.IntegerField(u'Количество', default=1)

    def __unicode__(self):
        return self.product.title

    class Meta:
        verbose_name = "продукты в корзине"
        verbose_name_plural = "Продукты в корзине"

    def cost_of_products(self):
        return self.product.price * self.quantity


class Order(models.Model):
    name = models.CharField(u'ФИО', max_length=64)
    phone = models.CharField(u'Номер телефона', max_length=11, help_text=u'Мы позвоним вам для уточнения заказа.')
    email = models.EmailField(u'Email', max_length=32, blank=True, null=True, help_text=u'Не обязательно, но мы туда пришлем данные о заказе.')
    isDelivery = models.BooleanField(u'Нужна ли доставка', default=False, help_text=u'Нужна ли доставка ?')
    address = models.CharField(u'Адрес', max_length=128, blank=True, null=True, help_text=u'Укажите адрес, для доставки')

    cart = models.ForeignKey(Cart, null=True, related_name='products')
    payment_type = models.CharField(u'Способ оплаты', max_length=30, choices=PAYMENT_TYPE, default=0, help_text=u'Выберите способ оплаты')
    price = models.IntegerField(u'Стоимость', editable=False)
    secret = models.CharField(max_length=60)
    add_date = models.DateTimeField(u'Дата оформления', auto_now_add=True)

    isAgreed = models.BooleanField(u'Согласовано', default=False)
    isPaid = models.BooleanField(u'Оплачено', default=False)
    isDelivered = models.BooleanField(u'Доставлено', default=False)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = "заказы"
        verbose_name_plural = "Заказы"

    @staticmethod
    def get_random_id():
        return uuid.uuid1()

    def get_order_detail(self):
        return reverse('order_detail', args=[self.secret])

    def get_absolute_url(self):
        return '/cart/order/%s' % self.secret

catalog/models.py
# coding: utf-8
from __future__ import unicode_literals
from django.db import models
from sorl.thumbnail import get_thumbnail
from importlib import import_module
from sys import getsizeof


def get_product_image_path(instance, filename):
    return 'products/%s/%s' % (instance.slug, filename)


def get_product_image_image_path(instance, filename):
    return 'products/%s/%s' % (instance.product.slug, filename)


def get_max_price():
    products = Product.objects.all()
    max_price = 0
    for product in products:
        if product.price > max_price:
            max_price = product.price
    return max_price


def get_min_price():
    products = Product.objects.all()
    min_price = getsizeof(int)
    for product in products:
        if product.price < min_price:
            min_price = product.price
    return min_price


class Product(models.Model):
    title = models.CharField(u'Наименование', max_length=64)
    description = models.TextField(u'Описание', max_length=4096)
    image = models.ImageField(u'Изображение', upload_to=get_product_image_path, blank=True, null=True)
    price = models.IntegerField(u'Стоимость')
    in_stoke_count = models.IntegerField(u'В наличии', default=0, help_text=u'сколько осталось на складе')

    sales_count = models.IntegerField(u'Продано', default=0, editable=False)
    returned = models.IntegerField(u'Возвращено', default=0, editable=False)
    slug = models.SlugField(u'URL', unique=True)
    add_date = models.DateField(u'Дата добавления', auto_now_add=True)

    @staticmethod
    def get_sales_count():
        summ = 0
        for product in Product.objects.all():
            summ += product.sales_count
        return summ

    @staticmethod
    def get_in_stoke_count():
        summ = 0
        for product in Product.objects.all():
            summ += product.in_stoke_count
        return summ

    def get_product_url(self):
        return '/catalog/%s' % self.slug

    def get_thumb_image(self):
        resize_img = get_thumbnail(self.image, '114x86', crop='center')
        return resize_img.url

    def get_catalog_image(self):
        resize_img = get_thumbnail(self.image, '270x220', crop='center')
        return resize_img.url

    def preview_image_url(self):
        return '<a href="' + str(self.id) + '/"><img src="%s"/></a>' % self.get_thumb_image()

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = u'продукт'
        verbose_name_plural = u'Продукт'

    preview_image_url.short_description = 'Изображение'
    preview_image_url.allow_tags = True


class ProductImage(models.Model):
    product = models.ForeignKey(Product, related_name='product_image', verbose_name="Продукт")
    image = models.ImageField(u'Изображения', upload_to=get_product_image_image_path)

    def get_main_image(self):
        resize_img = get_thumbnail(self.image, '500x375', crop='center')
        return resize_img

    def get_thumb_image(self):
        resize_img = get_thumbnail(self.image, '114x86', crop='center')
        return resize_img

    class Meta:
        verbose_name = "изображение"
        verbose_name_plural = "Изображения"

comments/models.py
# coding: utf-8
from __future__ import unicode_literals
from django.db import models


RATING = {
    '1': 1,
    '2': 2,
    '3': 3,
    '4': 4,
    '5': 5
}


class Comment(models.Model):
    message = models.TextField(u'Сообщение', max_length=4096, help_text=u'Введите Ваш отзыв здесь')
    name = models.CharField(u'Имя', max_length=64, help_text=u'Введите свое имя')
    email = models.CharField(u'Email', max_length=64, help_text=u'Введите свой email')
    rating = models.IntegerField(u'Оценка')
    slug = models.SlugField(u'URL', unique=True)
    add_date = models.DateTimeField(u'Дата добавления', auto_now_add=True)

    def __unicode__(self):
        return self.add_date

    class Meta:
        verbose_name = u'комментарии'
        verbose_name_plural = u'Комментарий'

cart/forms.py
from django.forms import ModelForm, HiddenInput
from models import Cart, ProductInCart, Order


class ProductInCartForm(ModelForm):
    class Meta:
        model = ProductInCart
        exclude = ['cart']


class OrderForm(ModelForm):
    class Meta:
        model = Order
        exclude = ["isAgreed", "secret", "cart", "isPaid", "isDelivered", "price"]

cart/views.py
# coding: utf-8
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.core.urlresolvers import reverse
from django.shortcuts import render, render_to_response, get_object_or_404, redirect
from models import Cart, ProductInCart, Order
import simplejson
from django.views.decorators.csrf import csrf_exempt
from forms import ProductInCartForm, OrderForm
from django.core.mail import send_mail, mail_admins
from vr_project import settings
from django.template.loader import render_to_string


def cart(request):
    if request.session.get("cart_id", False):
        try:
            cart = Cart.objects.get(id=request.session.get("cart_id"))
        except Cart.DoesNotExist:
            cart = Cart.objects.create()
            request.session["cart_id"] = cart.id
    else:
        cart = Cart.objects.create()
        request.session["cart_id"] = cart.id

    if request.method == 'POST':
        return render_to_response(
            'cart.html',
            {
                'cart': cart,
            }
        )
    else:
        return render_to_response(
            'cart.html',
            {
                'cart': cart,
            },
        )


@csrf_exempt
def add(request):
    if request.session.get("cart_id", False):
        try:
            cart = Cart.objects.get(id=request.session.get("cart_id"))
        except Cart.DoesNotExist:
            cart = Cart.objects.create()
            request.session["cart_id"] = cart.id
    else:
        cart = Cart.objects.create()
        request.session["cart_id"] = cart.id

    if request.method == 'POST':
        form = ProductInCartForm(request.POST)
        if form.is_valid():
            product = form.cleaned_data['product']
            quantity = form.cleaned_data['quantity']

            if ProductInCart.objects.filter(product__id=product.id, cart__id=cart.id).exists():
                product_in_cart = ProductInCart.objects.get(product__id=product.id, cart__id=cart.id)
                product_in_cart.quantity += quantity
                quantity = product_in_cart.quantity

                product_in_cart.save()
            else:
                form = form.save(commit=False)
                form.cart = cart
                form.save()
            if request.is_ajax():
                json_dict = {
                    "total_price": cart.total_price(),
                    "products": [{'id': product.id,
                                  'title': product.title,
                                  'price': product.price,
                                  'quantity': quantity,
                                  'cost': product.price * quantity}]
                }
                return HttpResponse(simplejson.dumps(json_dict), content_type="application/json")
            else:
                return HttpResponseRedirect(reverse('cart:cart'))
        else:
            json_dict = {"errors": [(k, v) for k, v in form.errors.items()]}
            return HttpResponse(simplejson.dumps(json_dict), content_type="application/json", status=400)

    else:
        json_dict = {"error": "Only post requests"}
        return HttpResponse(simplejson.dumps(json_dict), content_type="application/json", status=400)


@csrf_exempt
def remove(request):
    pass


@csrf_exempt
def order(request):
    if request.session.get("cart_id", False):
        try:
            cart = Cart.objects.get(id=request.session.get("cart_id"))
        except Cart.DoesNotExist:
            cart = Cart.objects.create()
    else:
        cart = Cart.objects.create()
        request.session["cart_id"] = cart.id

    if request.method == 'POST':
        order_form = OrderForm(request.POST)

        if order_form.is_valid():
            order_form = order_form.save(commit=False)
            order_form.cart = cart
            order_form.price = cart.total_price()
            order_form.secret = Order.get_random_id()
            order_form.save()

            #TODO: Убрать комментарий после дебага
            #del request.session["cart_id"]
            products_in_cart = ProductInCart.objects.filter(cart=cart.id)

            #TODO: Убрать комментарий после дебага
            #if not settings.DEBUG:
            # Отправляем письмо клиенту с данными о заказе
            if order_form.email:
                message = render_to_string('order_confirmation.txt',
                                           {
                                               'order': order_form,
                                               'products_in_cart': products_in_cart,
                                               'DOMAIN_NAME': settings.DOMAIN_NAME
                                           }
                )
                send_mail(settings.EMAIL_SUBJECT_PREFIX, message, settings.EMAIL_HOST_USER, [order_form.email, ])

            # Отправляем уведомительное письмо админу
            message = render_to_string('admin_order_confirmation.txt',
                                       {
                                           'order': order_form,
                                           'products_in_cart': products_in_cart,
                                           'DOMAIN_NAME': settings.DOMAIN_NAME
                                       }
            )
            mail_admins(settings.EMAIL_SUBJECT_PREFIX, message)

            return HttpResponseRedirect(reverse('cart:thanks', kwargs={'order_id': order_form.id}))
        else:
            return render_to_response(
                'order.html',
                {
                    'cart': cart,
                    'order_form': order_form
                }
            )
    else:
        order_form = OrderForm()

        return render_to_response(
            'order.html',
            {
                'cart': cart,
                'order_form': order_form
            }
        )


#TODO: Убрать @csrf_exempt где не надо
@csrf_exempt
def order_detail(request, secret):
    order = get_object_or_404(Order, secret=secret)
    form = OrderForm(instance=order)
    products_in_cart = ProductInCart.objects.filter(cart=order.cart)

    return render_to_response('order_item.html',
                              {
                                  'order': order,
                                  'form': form,
                                  'products_in_cart': products_in_cart
                              }
    )


def thanks(request, order_id):
    return render_to_response(
        'thanks.html',
        {
            'order': Order.objects.get(id=order_id),
            'DOMAIN_NAME': settings.DOMAIN_NAME
        }
    )

catalog/views.py
# coding: utf-8
from django.template import RequestContext
from django.shortcuts import render_to_response
from models import Product, get_max_price, get_min_price
import simplejson
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseBadRequest, JsonResponse
from django.template.loader import render_to_string


def catalog(request):
    if request.POST:
        if request.is_ajax():
            products = Product.objects.filter(price__lte=request.session['max_price'], price__gte=request.session['min_price'])
            data = render_to_string('catalog.ajax.html', {'products': products})
            return JsonResponse({'status': 200, 'result': data})
    else:
        products = Product.objects.all()

        return render_to_response(
            'catalog.html',
            {
                'products': products,
                'max_price': get_max_price,
                'min_price': get_min_price,
            }
        )


def product(request, product_slug):
    product = Product.objects.get(slug=product_slug)

    return render_to_response(
        'product.html',
        {
            'product': product,
        }
    )

comments/views.py
# coding: utf-8
from django.template import RequestContext
from django.shortcuts import render_to_response
from models import Comment
import simplejson
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseBadRequest, JsonResponse


def comment(request):
    comments = Comment.objects.all()

    return render_to_response(
        'comments.html',
        {
            'comment': comment,
        }
    )

main/views.py
# coding: utf-8
from django.template import RequestContext
from django.shortcuts import render_to_response
import simplejson
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseBadRequest, JsonResponse


def main(request):
    return render_to_response(
        'main.html',
        {

        },
    )

templates/cart.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}Корзина{% endblock %}

{% block page_content %}
    <button id="cart-selection" class="active-btn-in-cart">Корзина</button>
    <button id="order-selection">Заказ</button>
    <button id="thanks-selection">Подтверждение</button><br>

     {% for product in cart.products_in_cart.all %}
        Товар: {{ product.product.title }}<br>
        Количество: {{ product.quantity }}<br>
        Цена за единицу:{{ product.product.price }}<br>
        Всего за товар: {{ product.cost_of_products }}<br>
        </br></br></br>
    {% endfor %}

    {% if cart.total_price == 0 %}
        Корзина пуста<br>
    {% endif %}

    Всего: {{ cart.total_price }}р.
    </br></br>

    <a href="/" id="return_to_catalog">Обратно к каталогу</a>
    <form action="{% url "cart:order" %}" method="get" class="form">{% csrf_token %}
        <button class="button" id="order-create">Оформить заказ</button>
    </form>

{% endblock %}

templates/catalog.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}Каталог{% endblock %}

{% block page_content %}
    <!-- Page Content ================================================== -->
    <div class="row">
        <!-- Gallery Items ================================================== -->
        <div class="span12 gallery">
            <ul id="filterOptions" class="gallery-cats clearfix">
                <li class="active"><a href="#" class="all">All</a></li>
                <li><a href="#" class="illustration">Illustration</a></li>
                <li><a href="#" class="design">Design</a></li>
                <li><a href="#" class="video">Video</a></li>
                <li><a href="#" class="web">Web</a></li>
            </ul>
            <div class="row">
                <div class="span9">

                </div>
                <div class="span3">
                    <div id="price-slider" style="margin-bottom: 10px;"></div>
                    <div style="font-size: 14px; margin-left: 2px;">
                        Цена: <input id="catalog-price-min" style="width: 80px; margin: 1px;" type="text" placeholder="{{ min_price }}"> -
                        <input id="catalog-price-max" style="width: 80px; margin: 1px;" type="text" placeholder="{{ max_price }}"> р.
                    </div>
                </div>
            </div>

            <div class="row clearfix content">
                <ul class="gallery-post-grid holder">
                    {% for product in products %}
                        <!-- Gallery Item -->
                        <li class="span3 gallery-item" data-id="id-1" data-type="illustration">
                            <span class="gallery-hover-4col hidden-phone hidden-tablet">
                                <span class="gallery-icons">
                                    <a href="img/gallery/gallery-img-1-full.jpg" class="item-zoom-link lightbox" title="Custom Illustration" data-rel="prettyPhoto"></a>
                                    <a href="{{ product.get_product_url }}" class="item-details-link"></a>
                                </span>
                            </span>
                            <a href="{{ product.get_product_url }}"><img src="{{ product.get_catalog_image }}" alt="{{ product.title }}"></a>
                            <span class="project-details"><a href="{{ product.get_product_url }}">{{ product.title }}</a>{{ product.price }}р.</span>
                        </li>
                    {% endfor %}
                </ul>
            </div>

            <!-- Pagination -->
            <div class="pagination">
                <ul>
                <li class="active"><a href="#">Prev</a></li>
                <li class="active"><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">Next</a></li>
                </ul>
            </div>
        </div><!-- End gallery list-->
    </div><!-- End container row -->
{% endblock %}

templates/catalog_ajax.html
<ul class="gallery-post-grid holder">
    {% for product in products %}
        <!-- Gallery Item -->
        <li class="span3 gallery-item" data-id="id-1" data-type="illustration">
            <span class="gallery-hover-4col hidden-phone hidden-tablet">
                <span class="gallery-icons">
                    <a href="img/gallery/gallery-img-1-full.jpg" class="item-zoom-link lightbox" title="Custom Illustration" data-rel="prettyPhoto"></a>
                    <a href="{{ product.get_product_url }}" class="item-details-link"></a>
                </span>
            </span>
            <a href="{{ product.get_product_url }}"><img src="{{ product.get_catalog_image }}" alt="{{ product.title }}"></a>
            <span class="project-details"><a href="{{ product.get_product_url }}">{{ product.title }}</a>{{ product.price }}р.</span>
        </li>
    {% endfor %}
</ul>

templates/comments.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load staticfiles %}

{% block title %}Отзывы{% endblock %}

{% block page_content %}

{% endblock %}

templates/order.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}Заказ{% endblock %}

{% block page_content %}
    <!--<form action="{% url "cart:order" %}" method="post" class="form">{% csrf_token %}-->
        <!--{{ order_form.non_field_errors }}-->
        <!--<div class="fieldWrapper">-->
            <!--{{ order_form.name.errors }}-->
            <!--<label for="id_name">Укажиите Ваше ФИО</label>-->
            <!--{{ order_form.name }}-->
        <!--</div>-->
        <!--<div class="fieldWrapper">-->
            <!--{{ order_form.phone.errors }}-->
            <!--<label for="id_phone">Укажите номер телефона</label>-->
            <!--{{ order_form.phone }}-->
        <!--</div>-->
        <!--<div class="fieldWrapper">-->
            <!--{{ order_form.email.errors }}-->
            <!--<label for="id_email">Не обязательно, укажите email</label>-->
            <!--{{ order_form.email }}-->
        <!--</div>-->
        <!--<div class="fieldWrapper">-->
            <!--{{ order_form.isDelivery.errors }}-->
            <!--<label for="id_isDelivery">Нужна доставка ?</label>-->
            <!--{{ order_form.isDelivery }}-->
        <!--</div>-->
        <!--<div class="fieldWrapper">-->
            <!--{{ order_form.address.errors }}-->
            <!--<label for="id_address">Укажите адрес для доставки</label>-->
            <!--{{ order_form.address }}-->
        <!--</div>-->
        <!--<button class="button" id="button-order">-->
            <!--<span class="">Заказать!</span>-->
        <!--</button>-->
    <!--</form>-->
    <form action="{% url "cart:order" %}" method="post">
        {% csrf_token %}
        {{ order_form }}
    <input type="submit" value="Submit" />
</form>
{% endblock %}

templates/order_item.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}Заказ #{{ order.id }}{% endblock %}

{% block page_content %}
    {% for product in products_in_cart %}
        {{ product }}<br>
    {% endfor %}
    {{ order.price }}<br>
    {{ order_url }}
{% endblock %}

templates/product.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}{{ product.title }}{% endblock %}

{% block page_content %}
    {{ product.title }}<br>
    <img src="{{ product.get_thumb_image }}"><br>
    {{ product.price }}<br><br>
    <form action="{% url "cart:add" %}" method="post" class="form">{% csrf_token %}
        Кол-во
        <div class="wrap-qty">
            <span class="add-down add-action">-</span>
            <input type="text" name="quantity" size="2" value="1"/>
            <span class="add-up add-action">+</span>
        </div>
        <input type="hidden" name="product" value="{{ product.id }}"/>

        <button class="button" id="button-cart">
            <span class=""> Купить</span>
        </button>
    </form>
{% endblock %}

templates/thanks.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}{{ product.title }}{% endblock %}

{% block page_content %}
    Спасибо за заказ! Мы скоро свяжемся с Вами!
    Данные о Вашем заказе можно отслеживать на <a href="http://{{ DOMAIN_NAME }}{{ order.get_absolute_url }}">этой странице</a>
{% endblock %}